name: Dockerized Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        docker build -t my-docker-image ./path/to/dockerfile
      working-directory: ./  # Set the working directory where the Dockerfile is located

    - name: Run Docker Container
      run: |
        docker run -d -p 8080:3000 my-docker-image
